config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  resources :producers

  resources :animes do
    collection do
      get :download
      post :upload_video
    end
  end

  
  devise_for :users
  get 'payments/webhooks'
  post 'payments/webhooks'
  get 'home/index'
  get 'payment' => "payments#payment"
  post 'checkout' => "payments#checkout"

  root 'home#index'

end

app/models/anime.rb
class Anime < ActiveRecord::Base
  extend FriendlyId
  friendly_id :slug_candidates, use: :slugged
  mount_uploader :image, ImageUploader
  
  belongs_to :producer
  has_many :videos, dependent: :destroy
  accepts_nested_attributes_for :videos, reject_if: :all_blank, allow_destroy: true
  has_and_belongs_to_many :genres

  validates :title, :description, :image, :producer, :status, presence: true
  searchkick word_middle: [:title]
  # default_scope { order('created_at DESC') } 

  def search_data
    {
      title: title,
      status: status,
      genres: genres.pluck(:name),
      producer: producer.name,
      start_aired: start_aired,
      end_aired: end_aired
    }
  end

  def slug_candidates
    [
      :title,
      [:title, :id]
    ]
  end

  def producer_name
    producer.name
  end
end

app/controllers/animes_controller.rb
class AnimesController < ApplicationController
  before_action :set_anime, only: [:show, :edit, :update, :destroy]
  before_action :set_searching_conditions, only: :index
  
  respond_to :html

  def index
    # @animes = Anime.search (params[:keyword].present? ? params[:keyword] : '*'),
    #   fields: [{ title: :word_middle }],
    #   where: @condition,
    #   order: { start_aired: "desc" },
    #   page: params[:page],
    #   per_page: 18
    @animes = Anime.page(params[:page]).per(18)

    respond_with(@animes)
  end

  def show
    respond_with(@anime)
  end

  def new
    @anime = Anime.new
    respond_with(@anime)
  end

  def edit
  end

  def create
    @anime = Anime.new(anime_params)
    @anime.save
    respond_with(@anime)
  end

  def update
    @anime.update(anime_params)
    respond_with(@anime)
  end

  def destroy
    @anime.destroy
    respond_with(@anime)
  end

  def autocomplete
    render json: Anime.search(params[:query], fields: [{title: :word_middle}], limit: 10).map(&:title)
  end

  def download
    video = Video.find(params[:id])
    send_file video.file.path
  end

  private

    def set_anime
      @anime = Anime.friendly.find(params[:id])
    end

    def anime_params
      params.require(:anime).permit(:title, :description, :episodes, :status, :start_aired, :end_aired, :producer_id, :image, :duration) #, videos_attributes: [:id, :title, :description, :file, :_destroy])
    end

    def set_searching_conditions
      @condition = {}
      @condition[:status] = params[:status] if params[:status].present?
      @condition[:genres] = params[:genre] if params[:genre].present?
      @condition[:producer] = params[:producer] if params[:producer].present?
      @condition[:start_aired]= {gte: params[:gte].to_date} if params[:gte].present?
      @condition[:end_aired]= {lte: params[:lte].to_date} if params[:lte].present?
    end
end

app/helpers/animes_helper.rb
module AnimesHelper
end

app/views/animes/_form.html.slim
section#registration.container
  = form_for @anime, html: {class: "center", id: "form-anime"} do |f|
    - if @anime.errors.any?
      #error_explanation
        h2 = "#{pluralize(@anime.errors.count, "error")} prohibited this anime from being saved:"
        ul
          - @anime.errors.full_messages.each do |message|
            li = message
    fieldset.registration-form
      .form-group
        = f.text_field :title, class: "form-control", placeholder: "Title"
      .form-group
        = f.text_area :description, class: "form-control", placeholder: "Enter description here .."
      .form-group
        = f.label :image
        = f.file_field :image
      .form-group
        = f.text_field :episodes, class: "form-control", placeholder: "Episodes"
      .form-group
        = f.select :status,  options_for_select(["Currently Airing", "Finished"], params[:status]), {prompt: "- select status-"}, {class: "form-control", placeholder: "Genre"}
      .form-group
        = f.text_field :start_aired, class: "form-control datepicker", placeholder: "Start aired"
      .form-group
        = f.text_field :end_aired, class: "form-control datepicker", placeholder: "End aired"
      .form-group
        = f.text_field :duration, class: "form-control", placeholder: "Duration per-episodes"
      .form-group
        = f.select(:producer_id, Producer.all.collect {|p| [p.name, p.id]}, {:include_blank => "Select"}, {:class => "form-control"} )
      .form-group
        = f.label :videos
        = f.hidden_field :video_ids
      #videos
        = f.fields_for :videos do |video|
          = render 'video_fields', f: video
        .links
          = link_to_add_association 'Add Video', f, :videos, class: "btn btn-default"
      br

      .form-group
        = f.submit "Save", class: "btn-loading button btn btn-info btn-md btn-block"

- content_for :javascript
  = javascript_include_tag "animes",  "data-turbolinks-track" => true

  javascript:
    var fileUploadErrors = {
      maxFileSize: 'File is too big',
      minFileSize: 'File is too small',
      acceptFileTypes: 'Filetype not allowed',
      maxNumberOfFiles: 'Max number of files exceeded',
      uploadedBytes: 'Uploaded bytes exceed file size',
      emptyResult: 'Empty file upload result'
    };

app/views/animes/_video_fields.html.slim
.nested-fields
  .form-group
    = f.text_field :title, class: "form-control", placeholder: "Video title"
  .form-group
    = f.text_area :description, class: "form-control", placeholder: "Enter description here .."
  .form-group
    = f.file_field :file, class: "video-upload"
  / .form-group
  /   = link_to "Upload Video", "javascript:void(0)", class: "btn btn-success uploadBtn"
  / .progress
  /   .progress-bar role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style=("width: 0%;") 
  = link_to_remove_association "Remove Video", f
  

app/views/animes/edit.html.slim
== render 'form'

app/views/animes/index.html.slim
- @page = "Anime List"
- content_for :title do
  = "Anime List"

section#portfolio.container
  / ul.portfolio-filter
  /   li
  /     a.btn.btn-default.active data-filter="*" href="#"  All
  /   li
  /     a.btn.btn-default data-filter=".bootstrap" href="#"  Bootstrap
  /   li
  /     a.btn.btn-default data-filter=".html" href="#"  HTML
  /   li
  /     a.btn.btn-default data-filter=".wordpress" href="#"  Wordpress
  /! /#portfolio-filter
  
  .portfolio-filter
    = form_tag animes_path, class: "form-inline", method: :get do
      .form-group
        = text_field_tag :keyword, params[:keyword], class: "form-control", placeholder: "Title"
      / .form-group
      /   = select_tag :producer, options_from_collection_for_select(Producer.all, "name", "name", params[:producer]), prompt: "- producer -", class: "form-control"
      .form-group
        = select_tag :genre, options_from_collection_for_select(Genre.all, "name", "name", params[:genre]), prompt: "- genre -", class: "form-control"
      .form-group
        = select_tag :status,  options_for_select(["Currently Airing", "Finished"], params[:status]), prompt: "- select status-", class: "form-control"
      .form-group
        = text_field_tag :gte, params[:gte], class: "form-control datepicker", placeholder: "Start Aired"
      .form-group
        = text_field_tag :lte, params[:lte], class: "form-control datepicker", placeholder: "End Aired"

      = submit_tag "Search", class: "btn btn-default"

      - if user_signed_in?
        = link_to new_anime_path, class: "btn btn-info pull-right"
          = fa_icon "pencil"
          |  New Anime


  ul.portfolio-items.col-3
    - @animes.each do |anime|
      li.portfolio-item.apps
        .item-inner
          = image_tag anime.image.large.url
          h5 = anime.title
          .overlay
            = link_to anime_path(anime), class: "preview btn btn-danger"
              = fa_icon "eye"

  .pagination.pagination-lg
    = paginate @animes

app/views/animes/new.html.slim
- @page = "Create New Anime"

== render 'form'

app/views/animes/show.html.slim
- meta title: @anime.title,
        description: @anime.description

- @page = @anime.title
- content_for :title
  = @anime.title
  
section#blog.container
  .row
    aside.col-sm-4.col-sm-push-8
      .widget.search
        form role="form" 
          .input-group
            input.form-control autocomplete="off" placeholder="Search" type="text" /
            span.input-group-btn
              button.btn.btn-danger type="button" 
                i.icon-search
      /! /.search
      .widget.ads
        .row
          .col-xs-6
            = image_tag "ads/ad1.jpg", class: "img-responsive img-rounded"
          .col-xs-6
            = link_to "#"
              = image_tag "ads/ad2.png", class: "img-responsive img-rounded"
        p
        .row
          .col-xs-6
            = link_to "#"
              = image_tag "ads/ad3.png", class: "img-responsive img-rounded"
          .col-xs-6
            = link_to "#"
              = image_tag "ads/ad4.png", class: "img-responsive img-rounded"

      /! /.ads
      .widget.categories

        h3 Blog Categories
        .row
          .col-sm-6
            ul.arrow
              li
                a href="#"  Development
              li
                a href="#"  Design
              li
                a href="#"  Updates
              li
                a href="#"  Tutorial
              li
                a href="#"  News
          .col-sm-6
            ul.arrow
              li
                a href="#"  Joomla
              li
                a href="#"  Wordpress
              li
                a href="#"  Drupal
              li
                a href="#"  Magento
              li
                a href="#"  Bootstrap
      /! /.categories
      .widget.tags
        h3 Tag Cloud
        ul.tag-cloud
          li
            a.btn.btn-xs.btn-primary href="#"  CSS3
          li
            a.btn.btn-xs.btn-primary href="#"  HTML5
          li
            a.btn.btn-xs.btn-primary href="#"  WordPress
          li
            a.btn.btn-xs.btn-primary href="#"  Joomla
          li
            a.btn.btn-xs.btn-primary href="#"  Drupal
          li
            a.btn.btn-xs.btn-primary href="#"  Bootstrap
          li
            a.btn.btn-xs.btn-primary href="#"  jQuery
          li
            a.btn.btn-xs.btn-primary href="#"  Tutorial
          li
            a.btn.btn-xs.btn-primary href="#"  Update
      /! /.tags
      .widget.facebook-fanpage
        h3 Facebook Fanpage
        .widget-content
          .fb-like-box data-header="false" data-href="https://www.facebook.com/shapebootstrap" data-show-border="false" data-show-faces="true" data-stream="false" data-width="292" 
    .col-sm-8.col-sm-pull-4
      .blog
        .blog-item
          = image_tag @anime.image.url, class: "img-responsive img-blog"
          .blog-content
            h3 = @anime.title
            .pull-right = link_to "Edit", edit_anime_path(@anime) if user_signed_in?
            .entry-meta
              span
                i.icon-user
                | &nbsp;
                a href="#" = @anime.producer.name
              | &nbsp;
              span
                i.icon-calendar
                | &nbsp; Aired : 
                = @anime.start_aired.strftime("%b %d, %Y")
                | &nbsp; - 
                = @anime.end_aired.strftime("%b %d, %Y")

              span
                i.icon-comment
                a href="blog-item.html#comments"  3 Comments
            p = @anime.description
            p Downloads :
            - @anime.videos.each do |video|
              = link_to "Download #{video.title}", download_animes_path(id: video), { target: '_self' }
              br
              = videojs_rails sources: { mp4: video.file.url }, setup: "{}", controls: false, height: "400", width:"100%"
    
            hr/
            .tags
              i.icon-tags
              | &nbsp;
              | Genres : 
              | &nbsp;
              - @anime.genres.each do |genre|
                = link_to animes_path(genre: genre.name), class: "btn btn-xs btn-primary"
                  = genre.name
                | &nbsp;

            p &nbsp;
            .author.well
              .media
                .pull-left
                  = image_tag "chitoge.jpg", class: "avatar img-thumbnail", width: "85px"
                .media-body
                  .media-heading
                    strong John Doe
                  p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper.

            /! /.author
            / #comments
            /   #comments-list
            /     h3 3 Comments
            /     .media
            /       .pull-left
            /         img.avatar.img-circle alt="" src="images/blog/avatar1.png" /
            /       .media-body
            /         .well
            /           .media-heading
            /             strong> John Doe
            /             | \&nbsp;
            /             small 27 Aug 2013
            /             a.pull-right href="#" 
            /               i.icon-repeat
            /               | Reply
            /           p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
            /         .media
            /           .pull-left
            /             img.avatar.img-circle alt="" src="images/blog/avatar3.png" /
            /           .media-body
            /             .well
            /               .media-heading
            /                 strong> John Doe
            /                 | \&nbsp;
            /                 small 27 Aug 2013
            /                 a.pull-right href="#" 
            /                   i.icon-repeat
            /                   | Reply
            /               p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
            /         /! /.media
            /     /! /.media
            /     .media
            /       .pull-left
            /         img.avatar.img-circle alt="" src="images/blog/avatar2.png" /
            /       .media-body
            /         .well
            /           .media-heading
            /             strong> John Doe
            /             | \&nbsp;
            /             small 27 Aug 2013
            /             a.pull-right href="#" 
            /               i.icon-repeat
            /               | Reply
            /           p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo.
            /     /! /.media
            /   /! /#comments-list
            /   #comment-form
            /     h3 Leave a comment
            /     form.form-horizontal role="form" 
            /       .form-group
            /         .col-sm-6
            /           input.form-control placeholder="Name" type="text" /
            /         .col-sm-6
            /           input.form-control placeholder="Email" type="email" /
            /       .form-group
            /         .col-sm-12
            /           textarea.form-control placeholder="Comment" rows="8" 
            /       button.btn.btn-danger.btn-lg type="submit"  Submit Comment
              /! /#comment-form
            /! /#comments
        /! /.blog-item
    /! /.col-md-8