config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  resources :producers

  resources :animes do
    collection do
      get :download
      post :upload_video
    end
  end

  
  devise_for :users
  get 'payments/webhooks'
  post 'payments/webhooks'
  get 'home/index'
  get 'payment' => "payments#payment"
  post 'checkout' => "payments#checkout"

  root 'home#index'

end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!, except: :webhooks
  skip_before_action :verify_authenticity_token, only: :webhooks

  def payment
    @page = "Payment"
    @page_icon = "credit-card"
    gon.client_token = generate_client_token
  end

  def checkout
    result = current_user.payment(params)
    if result.success?
      redirect_to payment_path, notice: "Transaction successfull" 
    else
      flash[:alert] = "Something is went wrong, #{result.errors.first.message}"
      gon.client_token = generate_client_token

      render :payment
    end
  end

  def webhooks
    if request.get?
      challenge = params["bt_challenge"]
      challenge_response = Braintree::WebhookNotification.verify(challenge)
      render plain: challenge_response, status: 200
    else
      webhook_notification = Braintree::WebhookNotification.parse(
        params["bt_signature"],
        params["bt_payload"]
      )
      # puts "[Webhook Received #{webhook_notification.timestamp}] Kind: #{webhook_notification.kind} | Subscription: #{webhook_notification.subscription.id}"
      render plain: challenge_response, status: 200
    end
  end

  private

    def generate_client_token
      if current_user.has_payment_info?
        Braintree::ClientToken.generate(customer_id: current_user.braintree_customer_id)
      else
        Braintree::ClientToken.generate
      end
    end

end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_payment_form.html.slim
= form_tag checkout_path, id: "checkout", class: "checkout" do ||
  - unless current_user.has_payment_info?
    h4 Please enter your personal info:
    .form-group
      = text_field_tag "customer[first_name]", nil, class: "form-control", placeholder: "First Name"
    .form-group
      = text_field_tag "customer[last_name]", nil, class: "form-control", placeholder: "Last Name"
    .form-group
      = text_field_tag "customer[email]", nil, class: "form-control", placeholder: "Email"
    .form-group
      = text_field_tag "customer[phone]", nil, class: "form-control", placeholder: "Email"

  / h4 Please enter your payment details: 
  #payment-form
  .form-group
    = text_field_tag :amount, nil, class: "form-control", placeholder: "$ 200"
  .form-group
    = submit_tag "Pay", class: "btn btn-success"

app/views/payments/payment.html.slim
- meta title: "Payment",
      description: "Payment Donation"

- content_for :title
  | Payment

section#pricing
  .container
    .center
      h2 See our Pricings
      p.lead Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.

    /! /.center
    .gap
    #pricing-table.row
      .col-md-6.col-xs-6
        ul.plan.plan1
          li.plan-name
            h3 Basic Transaction
          = render 'payment_form'
      / ! /.col-md-3
      .col-md-6.col-xs-6.center
        ul.plan.plan2
          li.plan-name
            h3 Subscription
          = form_tag checkout_path, class: "checkout" do ||
            = hidden_field_tag 'type', 'subscription'
            - unless current_user.has_payment_info?
              h4 Please enter your personal info:
              .form-group
                = text_field_tag "customer[first_name]", nil, class: "form-control", placeholder: "First Name"
              .form-group
                = text_field_tag "customer[last_name]", nil, class: "form-control", placeholder: "Last Name"
              .form-group
                = text_field_tag "customer[email]", nil, class: "form-control", placeholder: "Email"
              .form-group
                = text_field_tag "customer[phone]", nil, class: "form-control", placeholder: "Email"

            / h4 Please enter your payment details: 
            #payment-subscription-form
            .form-group
              = text_field_tag :amount, nil, class: "form-control", placeholder: "$ 200"
            .form-group
              = submit_tag "Pay", class: "btn btn-primary"
      / /! /.col-md-3
      / .col-md-3.col-xs-6
      /   ul.plan.plan3
      /     li.plan-name
      /       h3 Advanced
      /     li.plan-price
      /       div
      /         span.price
      /           sup> $
      /           | 49
      /         small month
      /     li
      /       strong 50GB
      /       | Storage
      /     li
      /       strong 8GB
      /       | RAM
      /     li
      /       strong 1024GB
      /       | Bandwidth
      /     li
      /       strong Unlimited
      /       | Email Address
      /     li
      /       strong Forum
      /       | Support
      /     li.plan-action
      /       a.btn.btn-primary.btn-md href="#"  Signup
      / /! /.col-md-3
      / .col-md-3.col-xs-6
      /   ul.plan.plan4
      /     li.plan-name
      /       h3 Mighty
      /     li.plan-price
      /       div
      /         span.price
      /           sup> $
      /           | 99
      /         small month
      /     li
      /       strong 50GB
      /       | Storage
      /     li
      /       strong 8GB
      /       | RAM
      /     li
      /       strong 1024GB
      /       | Bandwidth
      /     li
      /       strong Unlimited
      /       | Email Address
      /     li
      /       strong Forum
      /       | Support
      /     li.plan-action
      /       a.btn.btn-primary.btn-md href="#"  Signup
      /! /.col-md-3
/! /#pricing



- content_for :javascript
  javascript:
    var clientToken = gon.client_token;
    
    braintree.setup(clientToken, "dropin", {
      container: "payment-form"
    });

    braintree.setup(clientToken, "dropin", {
      container: "payment-subscription-form"
    });

app/views/payments/payment_transaction.html.slim
h1 Payments#payment_transaction
p Find me in app/views/payments/payment_transaction.html.slim

app/views/payments/set_customer.html.slim
h1 Payments#set_customer
p Find me in app/views/payments/set_customer.html.slim