config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  resources :producers

  resources :animes do
    collection do
      get :download
      post :upload_video
    end
  end

  
  devise_for :users
  get 'payments/webhooks'
  post 'payments/webhooks'
  get 'home/index'
  get 'payment' => "payments#payment"
  post 'checkout' => "payments#checkout"

  root 'home#index'

end

app/models/producer.rb
class Producer < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
  default_scope { order('name') } 
  
  has_many :animes, dependent: :destroy

  validate :name
end

app/controllers/producers_controller.rb
class ProducersController < ApplicationController
  before_action :set_producer, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @producers = Producer.all
    respond_with(@producers)
  end

  def show
    respond_with(@producer)
  end

  def new
    @producer = Producer.new
    respond_with(@producer)
  end

  def edit
  end

  def create
    @producer = Producer.new(producer_params)
    @producer.save
    respond_with(@producer)
  end

  def update
    @producer.update(producer_params)
    respond_with(@producer)
  end

  def destroy
    @producer.destroy
    respond_with(@producer)
  end

  private
    def set_producer
      @producer = Producer.friendly.find(params[:id])
    end

    def producer_params
      params.require(:producer).permit(:name)
    end
end

app/helpers/producers_helper.rb
module ProducersHelper
end

app/views/producers/_form.html.slim
= form_for @producer do |f|
  - if @producer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@producer.errors.count, "error")} prohibited this producer from being saved:"
      ul
        - @producer.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :name
    = f.text_field :name
  .actions = f.submit

app/views/producers/edit.html.slim
h1 Editing producer

== render 'form'

= link_to 'Show', @producer
'|
= link_to 'Back', producers_path

app/views/producers/index.html.slim
h1 Listing producers

table
  thead
    tr
      th Name
      th
      th
      th

  tbody
    - @producers.each do |producer|
      tr
        td = producer.name
        td = link_to 'Show', producer
        td = link_to 'Edit', edit_producer_path(producer)
        td = link_to 'Destroy', producer, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Producer', new_producer_path

app/views/producers/new.html.slim
h1 New producer

== render 'form'

= link_to 'Back', producers_path

app/views/producers/show.html.slim
p#notice = notice

p
  strong Name:
  = @producer.name

= link_to 'Edit', edit_producer_path(@producer)
'|
= link_to 'Back', producers_path