config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  
  resources :producers

  resources :animes do
    collection do
      get :download
      post :upload_video
    end
  end

  
  devise_for :users
  get 'payments/webhooks'
  post 'payments/webhooks'
  get 'home/index'
  get 'payment' => "payments#payment"
  post 'checkout' => "payments#checkout"

  root 'home#index'

end

app/views/layouts/_menu.html.slim
header.navbar.navbar-inverse.navbar-fixed-top.wet-asphalt role="banner" 
  .container
    .navbar-header
      button.navbar-toggle data-target=".navbar-collapse" data-toggle="collapse" type="button" 
        span.sr-only Toggle navigation
        span.icon-bar
        span.icon-bar
        span.icon-bar
      = link_to root_path, class: "navbar-brand" do
        = image_tag "logo.png", alt: "logo"
    .collapse.navbar-collapse
      ul.nav.navbar-nav.navbar-right
        li
          = link_to animes_path
            = fa_icon 'youtube-play'
            | &nbsp;
            |  Animes
        / li
        /   = link_to producers_path
        /     = fa_icon 'users'
        /     |  Producers  

        - if user_signed_in?
          li.dropdown
            a.dropdown-toggle data-toggle="dropdown" href="#" 
              = image_tag current_user.avatar.thumb.url, width: "20px", class: "img-circle"
              | &nbsp;&nbsp;
              = "#{current_user.first_name} #{current_user.last_name}"
              | &nbsp;
              i.icon-angle-down
            ul.dropdown-menu
              li
                = link_to edit_user_registration_path
                  = fa_icon "pencil"
                  | &nbsp;&nbsp;
                  |  Edit Profile
              
              li
                = link_to payment_path
                  = fa_icon 'credit-card'
                  | &nbsp;
                  |  Payment

              li
                = link_to destroy_user_session_path, :method => :delete
                  = fa_icon "sign-out"
                  | &nbsp;&nbsp;
                  |  Logout

        / - else
        /   li
        /     = link_to new_user_session_path
        /       = fa_icon "sign-in"
        /       |  Sign In
        /   li
        /     = link_to new_user_registration_path
        /       = fa_icon "users"
        /       |  Sign Out
              
/! /header

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1"
    meta name="viewport" content="width=device-width, initial-scale=1.0"
    title= content_for?(:title) ? yield(:title) : "ervinarukii"
    = csrf_meta_tags
    = metamagic

    script src="http://maps.googleapis.com/maps/api/js?libraries=places&sensor=false" type="text/javascript" 
 
    /! Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application",  "data-turbolinks-track" => true


  body
    = include_gon
    = render 'layouts/menu'
    section#title.emerald
      .container
        .row
          .col-sm-6
            h1 
              = fa_icon "#{@page_icon}"
              |&nbsp;
              = @page
            p = @page_description
          .col-sm-6
            ul.breadcrumb.pull-right
              li
                = link_to "Home", root_path
              li.active = @page
    .container= bootstrap_flash
    
    = yield

    section#bottom.wet-asphalt
      .container
        .row
          .col-md-3.col-sm-6
            h4 About Us
            p Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante.
            p Pellentesque habitant morbi tristique senectus.
          /! /.col-md-3
          .col-md-3.col-sm-6
            h4 Company
            div
              ul.arrow
                li
                  a href="#"  The Company
                li
                  a href="#"  Our Team
                li
                  a href="#"  Our Partners
                li
                  a href="#"  Our Services
                li
                  a href="#"  Faq
                li
                  a href="#"  Conatct Us
                li
                  a href="#"  Privacy Policy
                li
                  a href="#"  Terms of Use
                li
                  a href="#"  Copyright
          /! /.col-md-3
          .col-md-3.col-sm-6
            h4 Latest Blog
            div
              .media
                .pull-left
                  img alt="" src="/assets/blog/thumb1.jpg" /
                .media-body
                  span.media-heading
                    a href="#"  Pellentesque habitant morbi tristique senectus
                  small.muted Posted 17 Aug 2013
              .media
                .pull-left
                  img alt="" src="/assets/blog/thumb2.jpg" /
                .media-body
                  span.media-heading
                    a href="#"  Pellentesque habitant morbi tristique senectus
                  small.muted Posted 13 Sep 2013
              .media
                .pull-left
                  img alt="" src="/assets/blog/thumb3.jpg" /
                .media-body
                  span.media-heading
                    a href="#"  Pellentesque habitant morbi tristique senectus
                  small.muted Posted 11 Jul 2013
          /! /.col-md-3
          .col-md-3.col-sm-6
            h4 Address
            address
              strong Twitter, Inc.
              br/
              | 795 Folsom Ave, Suite 600
              br/
              | San Francisco, CA 94107
              br/
              abbr title="Phone"  P:
              | (123) 456-7890
            h4 Newsletter
            form role="form" 
              .input-group
                input.form-control autocomplete="off" placeholder=("Enter your email") type="text" /
                span.input-group-btn
                  button.btn.btn-danger type="button"  Go!
          /! /.col-md-3
    /! /#bottom


    footer#footer.midnight-blue
      .container
        .row
          .col-sm-6
            | &copy; 2013 
            a href="http://shapebootstrap.net/" target="_blank" title=("Free Twitter Bootstrap WordPress Themes and HTML templates")  ShapeBootstrap
            |  All Rights Reserved.
          .col-sm-6
            ul.pull-right
              li
                a href="#"  Home
              li
                a href="#"  About Us
              li
                a href="#"  Faq
              li
                a href="#"  Contact Us
              li
                a#gototop.gototop href="#" 
                  i.icon-chevron-up
              /! #gototop
    /! /#footer

    = yield :javascript